"""Private checked-artifact recovery-record schema.

These records are durable implementation protocol, not public GwzCore service
messages. Keeping them in a separate taut schema prevents internal recovery
state from becoming an accidental client API while retaining one authoritative,
generated canonical wire model.
"""

from taut.ir.dsl import BYTES, INT, Enum, F, List, Msg, Ref, schema


SCHEMA = schema(
    Enum("CheckedPathComponentMode",
         sensitive=0,
         ascii_case_fold=1),
    Enum("CheckedDurableIdentityKind",
         linux_ext4=0,
         mac=1,
         windows_ntfs=2),
    Enum("CheckedAdmissionState",
         idle=0,
         preparing=1),
    Enum("CheckedCleanupAlias",
         source=0,
         goal=1,
         authority=2),
    Enum("CheckedCatalogRootKind",
         workspace=0,
         git_directory=1),
    Enum("CheckedManagedBootstrapPhase",
         install_components=0,
         retire_markers=1,
         complete=2),
    Enum("CheckedFilesystemProfile",
         linux_ext4_fs_ioc_getfsuuid_v1=0,
         mac_persistent_object_id_v1=1,
         windows_ntfs_file_id128_v1=2),
    Enum("CheckedManagedParentPurpose",
         merge_store=0,
         merge_archive=1,
         preservation_bundles=2,
         root_preservation_markers=3),

    Msg("CheckedDurablePathComponentV1",
        original_ascii=F(1, BYTES),
        parent_mode=F(2, Ref.CheckedPathComponentMode),
        canonical_ascii=F(3, BYTES),
        parent_durable_identity=F(4, Ref.CheckedDurableObjectIdentityV1)),
    Msg("CheckedDurablePathV1",
        components=F(1, List(Ref.CheckedDurablePathComponentV1))),

    # Variant-specific fields are validated by the semantic adapter. Taut owns
    # the field tags and canonical encoding; Rust owns the supported-profile
    # invariants and exposes a closed enum to the rest of checked_artifact.
    Msg("CheckedDurableObjectIdentityV1",
        kind=F(1, Ref.CheckedDurableIdentityKind),
        linux_external_filesystem_uuid=F(2, BYTES, optional=True),
        linux_handle_type=F(3, INT, optional=True),
        linux_persistent_handle=F(4, BYTES, optional=True),
        mac_volume_uuid=F(5, BYTES, optional=True),
        mac_persistent_object_id=F(6, BYTES, optional=True),
        windows_volume_guid_utf16le=F(7, BYTES, optional=True),
        windows_file_id_128=F(8, BYTES, optional=True)),

    Msg("CheckedManagedBootstrapInputV1",
        spec_digest=F(1, BYTES),
        component_count=F(2, INT)),
    Msg("CheckedActionScheduleV1",
        barrier_count=F(1, INT),
        bootstraps=F(2, List(Ref.CheckedManagedBootstrapInputV1)),
        cleanup_aliases=F(3, List(Ref.CheckedCleanupAlias)),
        schedule_digest=F(4, BYTES),
        managed_plan_digest=F(5, BYTES)),
    Msg("CheckedActionCapacityReservationV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        schedule=F(3, Ref.CheckedActionScheduleV1),
        record_digest=F(4, BYTES)),
    Msg("CheckedActionDirectoryAdmissionV1",
        state=F(1, Ref.CheckedAdmissionState),
        action_digest=F(2, BYTES, optional=True),
        request_owner_binding=F(3, BYTES, optional=True),
        capacity_schedule_sha256=F(4, BYTES, optional=True),
        staging_name=F(5, BYTES, optional=True),
        final_action_name=F(6, BYTES, optional=True),
        resident_reservation_sha256=F(7, BYTES, optional=True),
        record_digest=F(8, BYTES)),

    Msg("CheckedAuthorityV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        schedule_digest=F(3, BYTES),
        reservation_digest=F(4, BYTES),
        artifact_root=F(5, Ref.CheckedDurablePathV1),
        retained_parent_identity=F(6, Ref.CheckedDurableObjectIdentityV1),
        source=F(7, Ref.CheckedDurableLeafFingerprintV1),
        expected_sha256=F(8, BYTES),
        goal_sha256=F(9, BYTES),
        record_id=F(10, BYTES)),

    Msg("CheckedCatalogBootstrapV1",
        root_kind=F(1, Ref.CheckedCatalogRootKind),
        support_profile=F(2, Ref.CheckedFilesystemProfile),
        durable_target_digest=F(3, BYTES),
        historical_collision_digest=F(4, BYTES),
        retained_parent_identity=F(5, Ref.CheckedDurableObjectIdentityV1),
        retained_parent_path=F(6, Ref.CheckedDurablePathV1),
        staging_name=F(7, BYTES),
        final_name=F(8, BYTES),
        catalog_anchor_a_name=F(9, BYTES),
        catalog_anchor_b_name=F(10, BYTES),
        record_id=F(11, BYTES),
        bootstrap_ownership_token=F(12, BYTES)),

    Msg("CheckedInfrastructureV1",
        catalog_format=F(1, INT),
        catalog_root_identity=F(2, Ref.CheckedDurableObjectIdentityV1),
        catalog_anchor_identity=F(3, Ref.CheckedDurableObjectIdentityV1),
        roaming_anchor_identity=F(4, Ref.CheckedDurableObjectIdentityV1),
        retired_root_identity=F(5, Ref.CheckedDurableObjectIdentityV1),
        catalog_bootstrap_record_id=F(6, BYTES),
        admission_active_name=F(7, BYTES),
        admission_scratch_name=F(8, BYTES),
        admission_staging_name=F(9, BYTES),
        record_digest=F(10, BYTES),
        bootstrap_ownership_token=F(11, BYTES),
        staging_directory_identity=F(12, Ref.CheckedDurableObjectIdentityV1)),

    Msg("CheckedBarrierIntentV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        schedule_digest=F(3, BYTES),
        ordinal=F(4, INT),
        catalog_anchor_identity=F(5, Ref.CheckedDurableObjectIdentityV1),
        private_home_parent_identity=F(6, Ref.CheckedDurableObjectIdentityV1),
        private_home_name=F(7, BYTES),
        target_parent_identity=F(8, Ref.CheckedDurableObjectIdentityV1),
        target_path_profile=F(9, Ref.CheckedDurablePathV1),
        reserved_target_leaf=F(10, BYTES),
        intent_id=F(11, BYTES),
        reservation_digest=F(12, BYTES)),

    Msg("CheckedManagedBootstrapComponentV1",
        component_ascii=F(1, BYTES),
        staging_name=F(2, BYTES),
        final_name=F(3, BYTES),
        marker_name=F(4, BYTES),
        global_component_ordinal=F(5, INT),
        ownership_marker_id=F(6, BYTES, optional=True),
        ownership_marker_intent_id=F(7, BYTES, optional=True),
        installed_identity=F(8, Ref.CheckedDurableObjectIdentityV1, optional=True),
        installed_mode=F(9, Ref.CheckedPathComponentMode, optional=True),
        installed_path=F(10, Ref.CheckedDurablePathV1, optional=True),
        ownership_marker_object_identity=F(
            11, Ref.CheckedDurableObjectIdentityV1, optional=True)),
    Msg("CheckedManagedParentBootstrapIntentV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        reservation_digest=F(3, BYTES),
        schedule_digest=F(4, BYTES),
        spec_digest=F(5, BYTES),
        bootstrap_ordinal=F(6, INT),
        generation_ordinal=F(7, INT),
        generation_start=F(8, INT),
        component_start=F(9, INT),
        retained_parent_identity=F(10, Ref.CheckedDurableObjectIdentityV1),
        retained_parent_mode=F(11, Ref.CheckedPathComponentMode),
        retained_parent_path=F(12, Ref.CheckedDurablePathV1),
        components=F(13, List(Ref.CheckedManagedBootstrapComponentV1)),
        ownership_token=F(14, BYTES),
        predecessor_intent_id=F(15, BYTES, optional=True),
        phase=F(16, Ref.CheckedManagedBootstrapPhase),
        cursor=F(17, INT),
        intent_id=F(18, BYTES),
        purpose=F(19, Ref.CheckedManagedParentPurpose),
        managed_plan_digest=F(20, BYTES)),

    Msg("CheckedOwnershipMarkerV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        schedule_digest=F(3, BYTES),
        intent_id=F(4, BYTES),
        bootstrap_ordinal=F(5, INT),
        local_component_ordinal=F(6, INT),
        global_component_ordinal=F(7, INT),
        component_ascii=F(8, BYTES),
        staging_name=F(9, BYTES),
        final_name=F(10, BYTES),
        ownership_token=F(11, BYTES),
        marker_id=F(12, BYTES)),

    Msg("CheckedDurableLeafFingerprintV1",
        identity=F(1, Ref.CheckedDurableObjectIdentityV1),
        # Fixed-width little-endian u64. Taut INT is signed i64 and must not
        # silently narrow valid filesystem lengths.
        length_u64le=F(2, BYTES),
        sha256=F(3, BYTES)),
    Msg("CheckedCleanupRowV1",
        alias=F(1, Ref.CheckedCleanupAlias),
        expected=F(2, Ref.CheckedDurableLeafFingerprintV1)),
    Msg("CheckedCleanupWorklistV1",
        action_digest=F(1, BYTES),
        request_owner_binding=F(2, BYTES),
        schedule_digest=F(3, BYTES),
        rows=F(4, List(Ref.CheckedCleanupRowV1)),
        reservation_digest=F(5, BYTES)),
)
