"""GWS v0 taut protocol schema."""

from taut.ir.dsl import BOOL, BYTES, INT, STR, Enum, F, List, Msg, Ref, method, schema, service

SCHEMA = schema(
    # ---- enums ------------------------------------------------------------
    Enum("ActionKind",
         create_workspace=0,
         init_from_sources=1,
         add_existing_repo=2,
         create_repo=3,
         materialize=4,
         status=5,
         snapshot=6,
         tag=7,
         pull_head=8,
         pull_snapshot=9,
         push=10),

    Enum("SourceKind",
         git=0,
         archive=1,
         package=2,
         local=3,
         generated=4),

    Enum("AggregateStatus",
         accepted=0,
         ok=1,
         noop=2,
         rejected=3,
         partial=4,
         failed=5),

    Enum("MemberStatus",
         planned=0,
         ok=1,
         noop=2,
         skipped=3,
         rejected=4,
         failed=5),

    Enum("MaterializeTargetKind",
         lock=0,
         head=1,
         snapshot=2,
         tag=3,
         commit=4),

    Enum("SyncBehavior",
         fetch_only=0,
         ff_only=1,
         merge=2,
         rebase=3,
         reset=4,
         driver_selected=5),

    Enum("PartialBehavior",
         atomic=0,
         partial=1),

    Enum("DestructiveBehavior",
         refuse=0,
         allow=1),

    Enum("UnsupportedMemberBehavior",
         fail=0,
         skip=1),

    Enum("PlannedAction",
         noop=0,
         clone=1,
         fetch=2,
         fast_forward=3,
         checkout=4,
         init_repo=5,
         add_manifest_member=6,
         write_manifest=7,
         write_lock=8,
         write_snapshot=9,
         write_tag=10,
         push=11),

    Enum("LockMatch",
         unknown=0,
         matches=1,
         differs=2,
         missing=3),

    Enum("StatusMode",
         summary=0,
         combined=1),

    Enum("StatusPathStyle",
         member_relative=0,
         workspace_relative=1),

    Enum("EventKind",
         operation_started=0,
         member_started=1,
         member_progress=2,
         member_finished=3,
         artifact_written=4,
         operation_finished=5,
         reset=6),

    Enum("Severity",
         debug=0,
         info=1,
         warn=2,
         error=3),

    Enum("GwsErrorCode",
         ok=0,
         invalid_request=1,
         workspace_not_found=2,
         workspace_already_exists=3,
         nested_workspace=4,
         manifest_not_found=5,
         manifest_invalid=6,
         schema_unsupported=7,
         member_not_found=8,
         member_inactive=9,
         path_escape=10,
         path_collision=11,
         path_reserved=12,
         unsupported_source_kind=13,
         unsupported_operation=14,
         dirty_member=15,
         diverged_member=16,
         missing_remote=17,
         snapshot_not_found=18,
         lock_not_found=19,
         tag_not_found=20,
         tag_invalid=21,
         remote_rejected=22,
         git_command_failed=23,
         external_tool_missing=24,
         operation_not_found=25,
         attribution_denied=26,
         permission_denied=27,
         io_error=28,
         internal_error=29),

    # ---- common request/response values ----------------------------------
    Msg("WorkspaceRef",
        F("root", 1, STR, optional=True),
        F("workspace_id", 2, STR, optional=True)),

    Msg("OperationActor",
        F("actor_id", 1, STR),
        F("display_name", 2, STR, optional=True),
        F("email", 3, STR, optional=True),
        F("authority", 4, STR, optional=True)),

    Msg("GitObjectIdentity",
        F("name", 1, STR),
        F("email", 2, STR),
        F("time_ms", 3, INT, optional=True),
        F("timezone_offset_minutes", 4, INT, optional=True)),

    Msg("OperationAttribution",
        F("actor", 1, Ref("OperationActor"), optional=True),
        F("git_author", 2, Ref("GitObjectIdentity"), optional=True),
        F("git_committer", 3, Ref("GitObjectIdentity"), optional=True),
        F("credential_ref", 4, STR, optional=True)),

    Msg("Selection",
        F("all", 1, BOOL, optional=True),
        F("member_ids", 2, List(STR)),
        F("paths", 3, List(STR))),

    Msg("OperationPolicy",
        F("partial", 1, Ref("PartialBehavior"), optional=True),
        F("destructive", 2, Ref("DestructiveBehavior"), optional=True),
        F("sync", 3, Ref("SyncBehavior"), optional=True),
        F("unsupported_member", 4, Ref("UnsupportedMemberBehavior"), optional=True),
        F("remote", 5, STR, optional=True),
        F("concurrency", 6, INT, optional=True)),

    Msg("RequestMeta",
        F("request_id", 1, STR),
        F("schema_version", 2, STR),
        F("workspace", 3, Ref("WorkspaceRef"), optional=True),
        F("selection", 4, Ref("Selection"), optional=True),
        F("policy", 5, Ref("OperationPolicy"), optional=True),
        F("dry_run", 6, BOOL, optional=True),
        F("attribution", 7, Ref("OperationAttribution"), optional=True)),

    Msg("ResponseMeta",
        F("request_id", 1, STR),
        F("schema_version", 2, STR),
        F("action", 3, Ref("ActionKind")),
        F("aggregate_status", 4, Ref("AggregateStatus")),
        F("operation_id", 5, STR, optional=True),
        F("message", 6, STR, optional=True),
        F("attribution", 7, Ref("OperationAttribution"), optional=True)),

    Msg("GwsError",
        F("code", 1, Ref("GwsErrorCode")),
        F("message", 2, STR),
        F("member_id", 3, STR, optional=True),
        F("member_path", 4, STR, optional=True),
        F("detail", 5, STR, optional=True)),

    # ---- model projections ------------------------------------------------
    Msg("RemoteSpec",
        F("name", 1, STR),
        F("url", 2, STR),
        F("fetch", 3, BOOL, optional=True),
        F("push", 4, BOOL, optional=True)),

    Msg("DesiredRef",
        F("branch", 1, STR, optional=True),
        F("commit", 2, STR, optional=True),
        F("git_tag", 3, STR, optional=True),
        F("local_only", 4, BOOL, optional=True)),

    Msg("SourceUrl",
        F("url", 1, STR),
        F("path", 2, STR, optional=True),
        F("remote_name", 3, STR, optional=True),
        F("branch", 4, STR, optional=True)),

    Msg("MemberSpec",
        F("member_id", 1, STR),
        F("path", 2, STR),
        F("source_id", 3, STR),
        F("source_kind", 4, Ref("SourceKind")),
        F("active", 5, BOOL),
        F("desired", 6, Ref("DesiredRef"), optional=True),
        F("remotes", 7, List(Ref("RemoteSpec")))),

    Msg("MaterializeTarget",
        F("kind", 1, Ref("MaterializeTargetKind")),
        F("name", 2, STR, optional=True),
        F("commit", 3, STR, optional=True)),

    Msg("ResolvedMemberState",
        F("member_id", 1, STR),
        F("path", 2, STR),
        F("source_id", 3, STR),
        F("source_kind", 4, Ref("SourceKind")),
        F("commit", 5, STR, optional=True),
        F("branch", 6, STR, optional=True),
        F("detached", 7, BOOL, optional=True),
        F("upstream", 8, STR, optional=True),
        F("dirty", 9, BOOL, optional=True),
        F("materialized", 10, BOOL),
        F("remotes", 11, List(Ref("RemoteSpec")))),

    Msg("GitStatus",
        F("member_id", 1, STR),
        F("branch", 2, STR, optional=True),
        F("detached", 3, BOOL),
        F("head", 4, STR, optional=True),
        F("upstream", 5, STR, optional=True),
        F("ahead", 6, INT, optional=True),
        F("behind", 7, INT, optional=True),
        F("staged", 8, INT),
        F("unstaged", 9, INT),
        F("untracked", 10, INT),
        F("dirty", 11, BOOL)),

    Msg("GitFileChange",
        F("member_id", 1, STR),
        F("member_path", 2, STR),
        F("repo_path", 3, STR),
        F("workspace_path", 4, STR),
        F("index_status", 5, STR),
        F("worktree_status", 6, STR),
        F("original_repo_path", 7, STR, optional=True)),

    Msg("GitMemberBranchStatus",
        F("member_id", 1, STR),
        F("member_path", 2, STR),
        F("label", 3, STR),
        F("branch", 4, STR, optional=True),
        F("detached", 5, BOOL),
        F("unborn", 6, BOOL),
        F("head", 7, STR, optional=True),
        F("upstream", 8, STR, optional=True),
        F("ahead", 9, INT, optional=True),
        F("behind", 10, INT, optional=True)),

    Msg("GitBranchGroup",
        F("label", 1, STR),
        F("member_ids", 2, List(STR)),
        F("member_paths", 3, List(STR))),

    Msg("GitBranchDifference",
        F("label", 1, STR),
        F("majority_label", 2, STR, optional=True),
        F("member_ids", 3, List(STR)),
        F("member_paths", 4, List(STR)),
        F("message", 5, STR, optional=True)),

    Msg("WorkspaceGitStatus",
        F("clean", 1, BOOL),
        F("file_changes", 2, List(Ref("GitFileChange"))),
        F("branches", 3, List(Ref("GitMemberBranchStatus"))),
        F("branch_groups", 4, List(Ref("GitBranchGroup"))),
        F("branch_differences", 5, List(Ref("GitBranchDifference")))),

    Msg("PlannedChange",
        F("action", 1, Ref("PlannedAction")),
        F("from_ref", 2, STR, optional=True),
        F("to_ref", 3, STR, optional=True),
        F("message", 4, STR, optional=True)),

    Msg("MemberResponse",
        F("member_id", 1, STR),
        F("member_path", 2, STR),
        F("source_kind", 3, Ref("SourceKind")),
        F("status", 4, Ref("MemberStatus")),
        F("error", 5, Ref("GwsError"), optional=True),
        F("planned", 6, Ref("PlannedChange"), optional=True),
        F("state", 7, Ref("ResolvedMemberState"), optional=True),
        F("git_status", 8, Ref("GitStatus"), optional=True),
        F("lock_match", 9, Ref("LockMatch"), optional=True)),

    Msg("ResponseEnvelope",
        F("meta", 1, Ref("ResponseMeta")),
        F("members", 2, List(Ref("MemberResponse"))),
        F("errors", 3, List(Ref("GwsError")))),

    Msg("OperationEvent",
        F("operation_id", 1, STR),
        F("request_id", 2, STR),
        F("sequence", 3, INT),
        F("timestamp_ms", 4, INT),
        F("kind", 5, Ref("EventKind")),
        F("severity", 6, Ref("Severity")),
        F("member_id", 7, STR, optional=True),
        F("member_path", 8, STR, optional=True),
        F("message", 9, STR, optional=True),
        F("member", 10, Ref("MemberResponse"), optional=True),
        F("error", 11, Ref("GwsError"), optional=True),
        F("attribution", 12, Ref("OperationAttribution"), optional=True)),

    Msg("OperationResult",
        F("operation_id", 1, STR),
        F("request_id", 2, STR),
        F("action", 3, Ref("ActionKind")),
        F("aggregate_status", 4, Ref("AggregateStatus")),
        F("started_at_ms", 5, INT),
        F("finished_at_ms", 6, INT),
        F("members", 7, List(Ref("MemberResponse"))),
        F("errors", 8, List(Ref("GwsError"))),
        F("attribution", 9, Ref("OperationAttribution"), optional=True)),

    # ---- action requests --------------------------------------------------
    Msg("CreateWorkspaceRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("workspace_root", 2, STR),
        F("workspace_id", 3, STR, optional=True)),

    Msg("InitFromSourcesRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("workspace_root", 2, STR),
        F("sources", 3, List(Ref("SourceUrl"))),
        F("target", 4, Ref("MaterializeTarget"), optional=True),
        F("workspace_id", 5, STR, optional=True)),

    Msg("AddExistingRepoRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("repository_path", 2, STR),
        F("member_path", 3, STR, optional=True),
        F("member_id", 4, STR, optional=True),
        F("source_id", 5, STR, optional=True)),

    Msg("CreateRepoRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("member_path", 2, STR),
        F("initial_branch", 3, STR, optional=True),
        F("member_id", 4, STR, optional=True),
        F("source_id", 5, STR, optional=True)),

    Msg("MaterializeRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("target", 2, Ref("MaterializeTarget"))),

    Msg("StatusRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("mode", 2, Ref("StatusMode"), optional=True),
        F("include_file_changes", 3, BOOL, optional=True),
        F("include_branch_summary", 4, BOOL, optional=True),
        F("path_style", 5, Ref("StatusPathStyle"), optional=True)),

    Msg("SnapshotRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("snapshot_id", 2, STR)),

    Msg("TagRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("tag_name", 2, STR)),

    Msg("PullHeadRequest",
        F("meta", 1, Ref("RequestMeta"))),

    Msg("PullSnapshotRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("snapshot_id", 2, STR)),

    Msg("PushRequest",
        F("meta", 1, Ref("RequestMeta")),
        F("remote", 2, STR, optional=True),
        F("refspec", 3, STR, optional=True)),

    # ---- action responses -------------------------------------------------
    Msg("CreateWorkspaceResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("InitFromSourcesResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("AddExistingRepoResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("CreateRepoResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("MaterializeResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("StatusResponse",
        F("response", 1, Ref("ResponseEnvelope")),
        F("workspace_git_status", 2, Ref("WorkspaceGitStatus"), optional=True)),
    Msg("SnapshotResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("TagResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("PullHeadResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("PullSnapshotResponse", F("response", 1, Ref("ResponseEnvelope"))),
    Msg("PushResponse", F("response", 1, Ref("ResponseEnvelope"))),

    service("GwsCore",
        method("create_workspace", role="in",
               params=[("request", Ref("CreateWorkspaceRequest"))],
               out=Ref("CreateWorkspaceResponse")),
        method("init_from_sources", role="in",
               params=[("request", Ref("InitFromSourcesRequest"))],
               out=Ref("InitFromSourcesResponse")),
        method("add_existing_repo", role="in",
               params=[("request", Ref("AddExistingRepoRequest"))],
               out=Ref("AddExistingRepoResponse")),
        method("create_repo", role="in",
               params=[("request", Ref("CreateRepoRequest"))],
               out=Ref("CreateRepoResponse")),
        method("materialize", role="in",
               params=[("request", Ref("MaterializeRequest"))],
               out=Ref("MaterializeResponse")),
        method("status", role="in",
               params=[("request", Ref("StatusRequest"))],
               out=Ref("StatusResponse")),
        method("snapshot", role="in",
               params=[("request", Ref("SnapshotRequest"))],
               out=Ref("SnapshotResponse")),
        method("tag", role="in",
               params=[("request", Ref("TagRequest"))],
               out=Ref("TagResponse")),
        method("pull_head", role="in",
               params=[("request", Ref("PullHeadRequest"))],
               out=Ref("PullHeadResponse")),
        method("pull_snapshot", role="in",
               params=[("request", Ref("PullSnapshotRequest"))],
               out=Ref("PullSnapshotResponse")),
        method("push", role="in",
               params=[("request", Ref("PushRequest"))],
               out=Ref("PushResponse")),
        method("events.subscribe", role="out", shape="log",
               params=[("operation_id", STR)],
               out=Ref("OperationEvent")),
        method("operation.result", role="out",
               params=[("operation_id", STR)],
               out=Ref("OperationResult"))),
)
