"""Candidate schema compatibility fixtures across retained and new readers."""

import importlib.util
import hashlib
import json
import os
import sys
from pathlib import Path

import pytest

TAUT_SOURCE = Path(__file__).resolve().parents[4] / "taut" / "src"
sys.path.insert(0, str(TAUT_SOURCE))

ROOT = Path(__file__).resolve().parents[1]
CORE_SCHEMA = ROOT.parents[1] / "protocol" / "gwz.taut.py"
OWNER_SCHEMA = ROOT.parents[2] / "gwz-transport" / "protocol" / "transport.ir.json"
CANDIDATE_SCHEMA = ROOT / "protocol" / "candidate.taut.py"

os.environ["GWZ_CORE_SCHEMA"] = str(CORE_SCHEMA)
os.environ["GWZ_TRANSPORT_SCHEMA"] = str(OWNER_SCHEMA)

from taut.ir.load import load_schema  # noqa: E402
from taut.wire import codec  # noqa: E402

spec = importlib.util.spec_from_file_location("candidate_admission", Path(__file__).with_name("admission.py"))
assert spec is not None and spec.loader is not None
admission = importlib.util.module_from_spec(spec)
spec.loader.exec_module(admission)

RETAINED_CODEC_PATH = ROOT / "candidate" / "retained_taut" / "taut" / "wire" / "codec.py"
retained_spec = importlib.util.spec_from_file_location("taut.wire.retained_codec", RETAINED_CODEC_PATH)
assert retained_spec is not None and retained_spec.loader is not None
retained_codec = importlib.util.module_from_spec(retained_spec)
retained_spec.loader.exec_module(retained_codec)

NEW = load_schema(CANDIDATE_SCHEMA)
OLD = load_schema(CORE_SCHEMA)


def _old_options():
    return {"default_identity": None, "remote_identities": [], "url_scheme": None}


def _old_capabilities():
    return {"file_identity": True, "exact_agent_identity": True}


def _old_request_meta():
    return {
        "request_id": "request-1",
        "schema_version": "gwz.protocol/v0",
        "workspace": None,
        "selection": None,
        "policy": None,
        "dry_run": None,
        "attribution": None,
        "transport": None,
        "invocation": None,
    }


def test_overlay_has_exact_additive_tags_and_missing_ok_contract():
    expected = {
        "TransportOptions": {"placement": 4, "endpoint_path_base": 5},
        "RequestMeta": {"transport_message": 10},
        "ResponseMeta": {"transport_message": 9},
        "TransportCapabilitiesResponse": {
            "message_versions": 3,
            "placements": 4,
            "schemes": 5,
            "auth_policies": 6,
            "message_limits": 7,
        },
        "TransportObservation": {
            "endpoint_id": 9,
            "connection_id": 10,
            "stream_id": 11,
            "reused": 12,
        },
    }
    assert NEW.enums["TransportPlacement"].members == {"local": 1, "cli": 2}
    for message_name, fields in expected.items():
        actual = {field.name: field for field in NEW.messages[message_name].fields}
        for field_name, tag in fields.items():
            field = actual[field_name]
            assert field.tag == tag
            assert field.optional is True
            assert field.missing_ok is True


def test_old_production_request_and_capability_snapshots_are_stable():
    # These are generated by the retained production schema, then checked as
    # bytes so the compatibility proof cannot accidentally use the candidate
    # schema under an old-reader label.
    assert codec.encode(OLD, "TransportOptions", _old_options()).hex() == "a301f6028003f6"
    assert (
        codec.encode(OLD, "RequestMeta", _old_request_meta()).hex()
        == "a90169726571756573742d31026f67777a2e70726f746f636f6c2f763003f604f605f606f607f608f609f6"
    )
    assert codec.encode(OLD, "TransportCapabilitiesResponse", _old_capabilities()).hex() == "a201f502f5"


def test_new_writer_old_schema_reader_ignores_new_tags():
    value = {
        **_old_options(),
        "placement": "cli",
        "endpoint_path_base": "/client/workspace",
    }
    decoded = codec.decode(OLD, "TransportOptions", codec.encode(NEW, "TransportOptions", value))
    assert decoded["default_identity"] is None
    assert decoded["remote_identities"] == []
    assert decoded["url_scheme"] is None
    assert set(decoded["__unknown__"]) == {4, 5}


def test_retained_old_python_decoder_reads_local_and_explicit_cli_additive_fixtures():
    for placement in ("local", "cli"):
        value = {
            **_old_options(),
            "placement": placement,
            "endpoint_path_base": "/client/workspace",
        }
        decoded = retained_codec.decode(
            OLD, "TransportOptions", codec.encode(NEW, "TransportOptions", value)
        )
        assert decoded["default_identity"] is None
        assert set(decoded["__unknown__"]) == {4, 5}


def test_retained_python_decoder_provenance_is_pinned():
    metadata = json.loads((RETAINED_CODEC_PATH.parents[2] / "PROVENANCE.json").read_text())
    assert metadata["revision"] == "733e8a78897a90f017f4726e4331aed95e8cb977"
    assert hashlib.sha256(RETAINED_CODEC_PATH.read_bytes()).hexdigest() == metadata["sha256"]


def test_retained_old_writer_new_schema_reader_defaults_new_fields():
    decoded = codec.decode(NEW, "TransportOptions", codec.encode(OLD, "TransportOptions", _old_options()))
    assert decoded["placement"] is None
    assert decoded["endpoint_path_base"] is None


def test_candidate_missing_null_and_malformed_values_have_distinct_rules():
    old_wire = codec.encode_struct(OLD, "TransportOptions", _old_options())
    absent = codec.decode_struct(NEW, "TransportOptions", old_wire, strict=True)
    assert absent["placement"] is None
    assert absent["endpoint_path_base"] is None

    null_wire = {**old_wire, 4: None, 5: None}
    null = codec.decode_struct(NEW, "TransportOptions", null_wire, strict=True)
    assert null["placement"] is None
    assert null["endpoint_path_base"] is None

    malformed = {**old_wire, 4: "cli"}
    with pytest.raises(codec.DecodeError):
        codec.decode_struct(NEW, "TransportOptions", malformed, strict=True)


def test_default_local_and_capability_gating_refuse_old_or_incomplete_results():
    assert admission.placement_or_local(None) == "local"
    capable = {
        "message_versions": [2],
        "placements": ["cli"],
        "schemes": ["ssh"],
        "auth_policies": ["ssh_ambient"],
        "message_limits": {
            "encoded_frame": 4096,
            "data_payload": 1024,
            "metadata_bytes": 256,
            "nesting": 10,
            "collection_entries": 128,
            "decode_allocation": 65536,
            "queued_bytes": 131072,
            "queued_frames": 8,
            "receive_window": 65536,
            "control_reserve_bytes": 4096,
            "control_reserve_frames": 2,
        },
    }
    assert admission.supports_cli(capable, "ssh_ambient")
    for key in ("message_versions", "placements", "schemes", "auth_policies", "message_limits"):
        incomplete = dict(capable)
        incomplete[key] = None
        assert not admission.supports_cli(incomplete, "ssh_ambient")
    unsafe = dict(capable)
    unsafe["message_limits"] = dict(capable["message_limits"])
    unsafe["message_limits"]["queued_frames"] = 0
    assert not admission.supports_cli(unsafe, "ssh_ambient")
    assert not admission.supports_cli(capable, "gh")
