#!/usr/bin/env python3
"""Unit tests and negative fixtures for the Bazel pin-drift gate.

Positive: the real gwz-dev tree passes (skipped, with the reason, on a
checkout that has no gwz-dev root -- the gate is a workspace-root gate and
its inputs are the root's `MODULE.bazel` and `Cargo.lock` plus
`gwz-cli/Cargo.toml`). Negative fixtures: a bumped version (the lock moved
under a pin, and a pin moved off the lock), a changed feature and a flipped
`default-features`, an added direct dependency, a removed one, an inexact
pin, an unscoped spec, a BUILD label off the spec set, and a missing input.
Each fixture is a synthetic four-file tree in a temporary directory so the
checker, not Bazel or Cargo, is the rejector.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).with_name("check_bazel_pin_drift.py")
WORKSPACE_ROOT = SCRIPT.resolve().parents[3]
REAL_INPUTS = (
    WORKSPACE_ROOT / "MODULE.bazel",
    WORKSPACE_ROOT / "Cargo.lock",
    WORKSPACE_ROOT / "gwz-cli" / "Cargo.toml",
    WORKSPACE_ROOT / "gwz-cli" / "BUILD.bazel",
)


def load_gate():
    """The checker as a module, for unit tests over its parsers."""
    spec = importlib.util.spec_from_file_location("check_bazel_pin_drift", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module  # dataclasses resolve their module here
    spec.loader.exec_module(module)
    return module


# The shape of gwz-dev's MODULE.bazel: one from_cargo hub for gwz-core, one
# from_specs hub for gwz-cli, every spec scoped to the latter.
MODULE_BAZEL = '''\
module(name = "gwz", version = "0.1.0")

bazel_dep(name = "rules_rust", version = "0.70.0")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

crate.from_cargo(
    name = "gwz_core_crates",
    cargo_lockfile = "//gwz-core:Cargo.lock",
    manifests = ["//gwz-core:Cargo.toml"],
    skip_cargo_lockfile_overwrite = True,
)

# Hub @crates: gwz-cli's direct crates.io deps, pinned by hand to //:Cargo.lock.
crate.spec(
    package = "clap",
    version = "=4.6.6",
    features = [
        "derive",
        "wrap_help",
    ],
    repositories = ["crates"],
)
crate.spec(
    package = "console",
    version = "=0.16.4",
    repositories = ["crates"],
)
crate.spec(
    package = "serde_json",
    version = "=1.0.151",
    repositories = ["crates"],
)
crate.from_specs(name = "crates")
use_repo(crate, "crates", "gwz_core_crates")
'''

CLI_MANIFEST = '''\
[package]
name = "gwz"
version = "0.2.0-dev"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }
console = "0.16"
gwz-core = { path = "../gwz-core" }
serde_json = "1"

[dev-dependencies]
git2 = "0.21"
sha2 = "0.10"
'''

CLI_BUILD = '''\
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "gwz_lib",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//gwz-core:gwz_core",
        "@crates//:clap",
        "@crates//:console",
        "@crates//:serde_json",
    ],
)
'''


def lock_package(name: str, version: str, dependencies: list[str] | None = None) -> str:
    lines = ["[[package]]", f'name = "{name}"', f'version = "{version}"']
    if dependencies is None:
        lines.append('source = "registry+https://github.com/rust-lang/crates.io-index"')
    else:
        lines.append("dependencies = [")
        lines.extend(f' "{dependency}",' for dependency in dependencies)
        lines.append("]")
    return "\n".join(lines) + "\n"


def cargo_lock(
    versions: dict[str, str] | None = None,
    cli_edges: list[str] | None = None,
    extra_packages: str = "",
) -> str:
    versions = versions or {"clap": "4.6.6", "console": "0.16.4", "serde_json": "1.0.151"}
    cli_edges = cli_edges or ["clap", "console", "git2", "gwz-core", "serde_json", "sha2"]
    text = "# This file is automatically @generated by Cargo.\nversion = 4\n\n"
    for name, version in sorted(versions.items()):
        text += lock_package(name, version) + "\n"
    text += lock_package("git2", "0.21.0") + "\n"
    text += lock_package("gwz", "0.2.0-dev", cli_edges) + "\n"
    text += lock_package("gwz-core", "0.1.0", []) + "\n"
    text += lock_package("sha2", "0.10.9") + "\n"
    text += extra_packages
    return text


class SyntheticTree:
    """A minimal gwz-dev root: MODULE.bazel, Cargo.lock, gwz-cli/{Cargo.toml,BUILD.bazel}."""

    def __init__(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name) / "gwz-dev"
        (self.root / "gwz-cli").mkdir(parents=True)
        self.module_bazel = self.root / "MODULE.bazel"
        self.cargo_lock = self.root / "Cargo.lock"
        self.cli_manifest = self.root / "gwz-cli" / "Cargo.toml"
        self.cli_build = self.root / "gwz-cli" / "BUILD.bazel"
        self.module_bazel.write_text(MODULE_BAZEL, encoding="utf-8")
        self.cargo_lock.write_text(cargo_lock(), encoding="utf-8")
        self.cli_manifest.write_text(CLI_MANIFEST, encoding="utf-8")
        self.cli_build.write_text(CLI_BUILD, encoding="utf-8")

    def edit(self, path: Path, old: str, new: str) -> None:
        text = path.read_text(encoding="utf-8")
        assert old in text, f"{old!r} not in {path}"
        path.write_text(text.replace(old, new), encoding="utf-8")

    def check(self, *extra: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--workspace-root", str(self.root), *extra],
            check=False,
            capture_output=True,
            text=True,
        )

    def cleanup(self) -> None:
        self.temporary.cleanup()


class BazelPinDriftTest(unittest.TestCase):
    def tree(self) -> SyntheticTree:
        tree = SyntheticTree()
        self.addCleanup(tree.cleanup)
        return tree

    def assert_refused(self, result: subprocess.CompletedProcess[str], *fragments: str) -> None:
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("bazel pin drift: failed", result.stderr)
        for fragment in fragments:
            self.assertIn(fragment, result.stderr)

    @unittest.skipUnless(
        all(path.is_file() for path in REAL_INPUTS),
        "no gwz-dev root beside this checkout (MODULE.bazel, Cargo.lock, gwz-cli/): the live "
        "gate is a workspace-root gate; its synthetic fixtures below still run",
    )
    def test_real_tree_passes(self) -> None:
        result = subprocess.run(
            [sys.executable, str(SCRIPT)], check=False, capture_output=True, text=True
        )
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertIn("bazel pin drift: ok", result.stdout)
        self.assertIn("3 pin(s) in hub `crates`", result.stdout)
        for name in ("clap", "console", "serde_json"):
            self.assertIn(f"{name} =", result.stdout)

    def test_synthetic_tree_passes(self) -> None:
        tree = self.tree()
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertIn("bazel pin drift: ok", result.stdout)
        self.assertIn("3 pin(s) in hub `crates` compared with 3 direct registry dependencies", result.stdout)
        self.assertIn("and 3 BUILD label(s)", result.stdout)

    def test_bumped_version_is_rejected_from_either_side(self) -> None:
        # The lock moved under the pin (a `cargo update` without re-pinning).
        tree = self.tree()
        tree.edit(tree.cargo_lock, 'name = "clap"\nversion = "4.6.6"', 'name = "clap"\nversion = "4.6.7"')
        self.assert_refused(tree.check(), "crate.spec 'clap' pins 4.6.6 but Cargo.lock resolved 4.6.7", "version drift")
        # The pin moved off the lock (an edit of MODULE.bazel alone).
        tree = self.tree()
        tree.edit(tree.module_bazel, 'version = "=1.0.151"', 'version = "=1.0.152"')
        self.assert_refused(tree.check(), "crate.spec 'serde_json' pins 1.0.152 but Cargo.lock resolved 1.0.151")

    def test_changed_feature_is_rejected(self) -> None:
        # The manifest gains a feature the pin does not carry.
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'features = ["derive", "wrap_help"]', 'features = ["derive", "wrap_help", "env"]')
        self.assert_refused(
            tree.check(),
            "crate.spec 'clap' features ['derive', 'wrap_help'] differ from gwz-cli/Cargo.toml's "
            "['derive', 'env', 'wrap_help']",
            "feature drift",
        )
        # The pin drops a feature the manifest still requests.
        tree = self.tree()
        tree.edit(tree.module_bazel, '        "wrap_help",\n', "")
        self.assert_refused(tree.check(), "crate.spec 'clap' features ['derive'] differ")
        # `default-features = false` in the manifest without `default_features = False` on the pin.
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'console = "0.16"', 'console = { version = "0.16", default-features = false }')
        self.assert_refused(
            tree.check(),
            "crate.spec 'console' default_features=True but gwz-cli/Cargo.toml says default-features=False",
        )
        # ... and the matching pin passes.
        tree.edit(
            tree.module_bazel,
            '    package = "console",\n    version = "=0.16.4",\n',
            '    package = "console",\n    version = "=0.16.4",\n    default_features = False,\n',
        )
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertIn("console =0.16.4 features [-] default_features=False", result.stdout)

    def test_added_direct_dependency_is_rejected(self) -> None:
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'serde_json = "1"\n', 'serde_json = "1"\nanyhow = "1"\n')
        tree.cargo_lock.write_text(
            cargo_lock(
                {"anyhow": "1.0.100", "clap": "4.6.6", "console": "0.16.4", "serde_json": "1.0.151"},
                ["anyhow", "clap", "console", "git2", "gwz-core", "serde_json", "sha2"],
            ),
            encoding="utf-8",
        )
        self.assert_refused(
            tree.check(),
            "direct dependency 'anyhow' has no crate.spec in hub `crates` (added dependency",
        )
        # A dependency added to the manifest but not yet to the lock is two
        # findings, not a crash: the missing pin and the missing lock edge.
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'serde_json = "1"\n', 'serde_json = "1"\nanyhow = "1"\n')
        self.assert_refused(tree.check(), "direct dependency 'anyhow' has no crate.spec")

    def test_removed_direct_dependency_is_rejected(self) -> None:
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'console = "0.16"\n', "")
        tree.cargo_lock.write_text(
            cargo_lock(
                {"clap": "4.6.6", "serde_json": "1.0.151"},
                ["clap", "git2", "gwz-core", "serde_json", "sha2"],
            ),
            encoding="utf-8",
        )
        self.assert_refused(
            tree.check(),
            "crate.spec 'console' is not a direct registry dependency of gwz-cli/Cargo.toml "
            "(removed dependency",
        )

    def test_a_dependency_the_lock_does_not_describe_is_a_finding(self) -> None:
        # The manifest and the pin agree, but the lock has no edge to it: the
        # lock is stale relative to the manifest (`cargo --locked` would refuse).
        tree = self.tree()
        tree.cargo_lock.write_text(
            cargo_lock(cli_edges=["clap", "git2", "gwz-core", "serde_json", "sha2"]),
            encoding="utf-8",
        )
        self.assert_refused(tree.check(), "Cargo.lock: no edge from the cli package to 'console'")

    def test_inexact_pin_is_rejected(self) -> None:
        for inexact in ("4.6.6", "^4.6.6", "=4.6", ">=4.6.6, <5"):
            tree = self.tree()
            tree.edit(tree.module_bazel, 'version = "=4.6.6"', f'version = "{inexact}"')
            self.assert_refused(tree.check(), f"crate.spec 'clap' version {inexact!r} is not an exact `=x.y.z` pin")

    def test_unscoped_and_shared_specs_are_rejected(self) -> None:
        # No `repositories`: the spec applies to every hub, including gwz-core's.
        tree = self.tree()
        tree.edit(
            tree.module_bazel,
            '    version = "=0.16.4",\n    repositories = ["crates"],\n',
            '    version = "=0.16.4",\n',
        )
        self.assert_refused(tree.check(), "crate.spec 'console' is unscoped (no `repositories`)")
        # Scoped to both hubs.
        tree = self.tree()
        tree.edit(
            tree.module_bazel,
            '    version = "=0.16.4",\n    repositories = ["crates"],\n',
            '    version = "=0.16.4",\n    repositories = ["crates", "gwz_core_crates"],\n',
        )
        self.assert_refused(tree.check(), "crate.spec 'console' is shared with ['gwz_core_crates']")
        # A spec scoped to another hub only is that hub's business.
        tree = self.tree()
        tree.edit(
            tree.module_bazel,
            'crate.from_specs(name = "crates")\n',
            'crate.spec(\n    package = "anyhow",\n    version = "=1.0.100",\n'
            '    repositories = ["other"],\n)\ncrate.from_specs(name = "other")\n'
            'crate.from_specs(name = "crates")\n',
        )
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertNotIn("anyhow", result.stdout)

    def test_build_labels_must_equal_the_spec_set(self) -> None:
        tree = self.tree()
        tree.edit(tree.cli_build, '        "@crates//:console",\n', "")
        self.assert_refused(tree.check(), "does not consume `@crates//:console` although hub `crates` pins it")
        tree = self.tree()
        tree.edit(tree.cli_build, '        "@crates//:console",\n', '        "@crates//:console",\n        "@crates//:anyhow",\n')
        self.assert_refused(tree.check(), "consumes `@crates//:anyhow` but hub `crates` pins no crate.spec 'anyhow'")
        # `--no-cli-build` leaves the labels out of the comparison.
        result = tree.check("--no-cli-build")
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertNotIn("BUILD label", result.stdout)

    def test_path_and_dev_dependencies_are_not_hub_members(self) -> None:
        # gwz-core (path) and the dev-dependencies never need a pin; a pin
        # for the path dependency is refused as a spec naming no dependency.
        tree = self.tree()
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        for absent in ("gwz-core", "git2", "sha2"):
            self.assertNotIn(f"{absent} =", result.stdout)
        tree.edit(
            tree.module_bazel,
            'crate.from_specs(name = "crates")\n',
            'crate.spec(\n    package = "gwz-core",\n    version = "=0.1.0",\n'
            '    repositories = ["crates"],\n)\ncrate.from_specs(name = "crates")\n',
        )
        self.assert_refused(tree.check(), "crate.spec 'gwz-core' is not a direct registry dependency")

    def test_a_renamed_dependency_is_compared_by_its_package_name(self) -> None:
        tree = self.tree()
        tree.edit(tree.cli_manifest, 'serde_json = "1"', 'json = { package = "serde_json", version = "1" }')
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertIn("serde_json =1.0.151", result.stdout)

    def test_two_lock_versions_of_a_direct_dependency_resolve_by_the_cli_edge(self) -> None:
        # The lock holds two `console` versions (some transitive dependency
        # wants the other); the cli edge is spelled `console 0.16.4`.
        tree = self.tree()
        tree.cargo_lock.write_text(
            cargo_lock(
                cli_edges=["clap", "console 0.16.4", "git2", "gwz-core", "serde_json", "sha2"],
                extra_packages=lock_package("console", "0.15.11"),
            ),
            encoding="utf-8",
        )
        result = tree.check()
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        self.assertIn("console =0.16.4 features [-] default_features=True <-> lock 0.16.4", result.stdout)
        # An unspelled edge into an ambiguous lock is an error, not a guess.
        tree.cargo_lock.write_text(
            cargo_lock(extra_packages=lock_package("console", "0.15.11")),
            encoding="utf-8",
        )
        result = tree.check()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertIn("edge 'console' of 'gwz' resolves to 2 packages", result.stderr)

    def test_missing_or_unparseable_input_is_an_error_not_a_pass(self) -> None:
        tree = self.tree()
        tree.module_bazel.unlink()
        result = tree.check()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertIn("cannot read MODULE.bazel", result.stderr)
        tree = self.tree()
        tree.cargo_lock.unlink()
        self.assertEqual(tree.check().returncode, 2)
        tree = self.tree()
        tree.cli_manifest.unlink()
        self.assertEqual(tree.check().returncode, 2)
        tree = self.tree()
        tree.cli_build.unlink()
        self.assertEqual(tree.check().returncode, 2)
        # A single-repo checkout has no root at all: still an error.
        tree = self.tree()
        result = tree.check("--workspace-root", str(tree.root / "absent"))
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        # Starlark `ast` cannot parse, and a hub that is not declared.
        tree = self.tree()
        tree.module_bazel.write_text(MODULE_BAZEL + "crate.spec(\n", encoding="utf-8")
        result = tree.check()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertIn("not Python-parseable Starlark", result.stderr)
        tree = self.tree()
        tree.edit(tree.module_bazel, 'crate.from_specs(name = "crates")\n', "")
        result = tree.check()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertIn('declares no `crate.from_specs(name = "crates")` hub', result.stderr)

    def test_parsers_read_the_real_shapes(self) -> None:
        gate = load_gate()
        specs, hubs = gate.parse_module_bazel(MODULE_BAZEL, Path("MODULE.bazel"))
        self.assertEqual(hubs, {"crates"})
        self.assertEqual(
            [(spec.package, spec.version, spec.features, spec.default_features, spec.repositories) for spec in specs],
            [
                ("clap", "=4.6.6", ("derive", "wrap_help"), True, ("crates",)),
                ("console", "=0.16.4", (), True, ("crates",)),
                ("serde_json", "=1.0.151", (), True, ("crates",)),
            ],
        )
        name, dependencies = gate.parse_cli_manifest(CLI_MANIFEST, Path("Cargo.toml"))
        self.assertEqual(name, "gwz")
        self.assertEqual([d.package for d in dependencies], ["clap", "console", "serde_json"])
        self.assertEqual(dependencies[0].features, ("derive", "wrap_help"))
        versions = gate.resolved_versions(gate.parse_cargo_lock(cargo_lock(), Path("Cargo.lock")), "gwz", Path("Cargo.lock"))
        self.assertEqual(
            versions,
            {"clap": "4.6.6", "console": "0.16.4", "git2": "0.21.0", "gwz-core": "0.1.0", "serde_json": "1.0.151", "sha2": "0.10.9"},
        )
        self.assertEqual(gate.build_labels(CLI_BUILD, "crates"), {"clap", "console", "serde_json"})


if __name__ == "__main__":
    unittest.main()
